spring.application.name=HealthTracker
spring.config.import=optional:file:.env[.properties]

jwt.secret=${JWT_SECRET}

#jdbc:postgresql://localhost:****/{name}
spring.datasource.url=${DBUrl}
spring.datasource.username=${DBUsername}
spring.datasource.password=${DBPassword}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


management.endpoints.web.exposure.include=health,info,metrics