spring.application.name=HealthTracker
spring.config.import=optional:file:.env[.properties]

jwt.secret=${JWT_SECRET}

#jdbc:postgresql://localhost:****/{name}
spring.datasource.url=${DBUrl}
spring.datasource.username=${DBUsername}
spring.datasource.password=${DBPassword}
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
